import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { createPublicClient, createWalletClient, custom, parseEther, keccak256, toBytes, type Abi, type Address, type Hex } from 'viem';
import ganache from 'ganache';
const require=createRequire(import.meta.url);
const solc=require('solc') as {compile:(input:string,callbacks:{import:(path:string)=>{contents?:string;error?:string}})=>string};
const input={language:'Solidity',sources:Object.fromEntries(['DuelEscrow.sol','ReentrantReceiver.sol'].map(n=>[n,{content:readFileSync(resolve('contracts/evm',n),'utf8')}])),settings:{evmVersion:'shanghai',optimizer:{enabled:true,runs:200},outputSelection:{'*':{'*':['abi','evm.bytecode.object']}}}};
const output=JSON.parse(solc.compile(JSON.stringify(input),{import:path=>{try{return {contents:readFileSync(resolve('node_modules',path),'utf8')};}catch{return {error:`Missing ${path}`};}}})) as {errors?:{severity:string;formattedMessage:string}[];contracts:Record<string,Record<string,{abi:Abi;evm:{bytecode:{object:string}}}>>};
const errors=output.errors?.filter(e=>e.severity==='error')??[];assert.equal(errors.length,0,errors.map(e=>e.formattedMessage).join('\n'));
mkdirSync('contracts/evm/artifacts',{recursive:true});writeFileSync('contracts/evm/artifacts/DuelEscrow.json',JSON.stringify(output.contracts['DuelEscrow.sol'].DuelEscrow,null,2));
const provider=ganache.provider({logging:{quiet:true},chain:{hardfork:'shanghai'},wallet:{totalAccounts:5,defaultBalance:1000}});
const transport=custom(provider);const client=createPublicClient({transport,cacheTime:0});const wallets=await provider.request({method:'eth_accounts',params:[]}) as Address[];const [owner,alice,bob,outsider,oracle]=wallets;const wallet=createWalletClient({transport});
const artifact=output.contracts['DuelEscrow.sol'].DuelEscrow;
const deployment=await wallet.deployContract({account:owner,chain:null,abi:artifact.abi,bytecode:`0x${artifact.evm.bytecode.object}`,args:[owner,oracle],gas:5000000n});const address=(await client.waitForTransactionReceipt({hash:deployment})).contractAddress!;
const send=async(from:Address,fn:string,args:unknown[]=[],value?:bigint)=>{const hash=await wallet.writeContract({account:from,chain:null,address,abi:artifact.abi,functionName:fn,args,value,gas:3000000n});const receipt=await client.waitForTransactionReceipt({hash});if(receipt.status!=='success')throw new Error(`Reverted: ${fn}`);return receipt;};
const read=async(fn:string,args:unknown[]=[])=>client.readContract({address,abi:artifact.abi,functionName:fn,args});
const advance=async(seconds:number)=>{await provider.request({method:'evm_increaseTime',params:[seconds]});await provider.request({method:'evm_mine',params:[]});};
const now=async()=>Number((await client.getBlock()).timestamp);
const hash=(s:string)=>keccak256(toBytes(s));const stake=parseEther('1');let count=0;
const check=async(name:string,fn:()=>Promise<void>)=>{await fn();count++;console.log(`PASS ${name}`);};
try{
  const id=hash('happy');await check('create / exact escrow accounting',async()=>{await send(alice,'createChallenge',[id,bob,86400,await now()+3600],stake);assert.equal(await read('totalLocked'),stake);});
  await check('wrong opponent rejected',async()=>{await assert.rejects(send(outsider,'acceptChallenge',[id],stake));});
  await check('unequal stake rejected',async()=>{await assert.rejects(send(bob,'acceptChallenge',[id],stake-1n));});
  await check('duplicate creation rejected',async()=>{await assert.rejects(send(alice,'createChallenge',[id,bob,86400,await now()+3600],stake));});
  await check('equal deposit / duplicate acceptance rejected',async()=>{await send(bob,'acceptChallenge',[id],stake);await assert.rejects(send(bob,'acceptChallenge',[id],stake));assert.equal(await read('totalLocked'),stake*2n);});
  await check('early settlement rejected',async()=>{await assert.rejects(send(oracle,'settleDuel',[id,1,hash('result')]));});await advance(86401);
  await check('unauthorized settlement rejected',async()=>{await assert.rejects(send(owner,'settleDuel',[id,1,hash('result')]));});
  await check('settle once / payout is pull-based',async()=>{await send(oracle,'settleDuel',[id,1,hash('result')]);assert.equal(await read('claimable',[alice]),stake*2n);await assert.rejects(send(oracle,'settleDuel',[id,1,hash('result')]));await send(alice,'claim');assert.equal(await read('totalClaimable'),0n);await assert.rejects(send(alice,'claim'));});
  await check('expiry / cancellation / duplicate refund',async()=>{const id=hash('expiry');await send(alice,'createChallenge',[id,bob,86400,await now()+10],stake);await assert.rejects(send(alice,'cancelExpiredChallenge',[id]));await advance(11);await assert.rejects(send(bob,'acceptChallenge',[id],stake));await send(alice,'cancelExpiredChallenge',[id]);await assert.rejects(send(alice,'cancelExpiredChallenge',[id]));await send(alice,'claim');});
  await check('tie refunds both deposits',async()=>{const id=hash('tie');await send(alice,'createChallenge',[id,bob,86400,await now()+100],stake);await send(bob,'acceptChallenge',[id],stake);await advance(86401);await send(oracle,'settleDuel',[id,0,hash('tie-result')]);assert.equal(await read('claimable',[alice]),stake);assert.equal(await read('claimable',[bob]),stake);await send(alice,'claim');await send(bob,'claim');});
  await check('pause is authorized / recovery remains available',async()=>{await assert.rejects(send(alice,'pause'));await send(owner,'pause');await assert.rejects(send(alice,'createChallenge',[hash('paused'),bob,86400,await now()+100],stake));await send(owner,'unpause');});
  await check('oracle outage timeout returns both stakes',async()=>{const id=hash('timeout');await send(alice,'createChallenge',[id,bob,86400,await now()+100],stake);await send(bob,'acceptChallenge',[id],stake);await assert.rejects(send(alice,'refundDuel',[id]));await advance(8*86400+1);await send(bob,'refundDuel',[id]);await send(alice,'claim');await send(bob,'claim');});
  await check('reentrant receiver cannot claim twice',async()=>{const a=output.contracts['ReentrantReceiver.sol'].ReentrantReceiver;const tx=await wallet.deployContract({account:owner,chain:null,abi:a.abi,bytecode:`0x${a.evm.bytecode.object}`,args:[address]});const receiver=(await client.waitForTransactionReceipt({hash:tx})).contractAddress!;const invoke=async(fn:string,args:unknown[]=[],value?:bigint)=>{const h=await wallet.writeContract({account:owner,chain:null,address:receiver,abi:a.abi,functionName:fn,args,value,gas:3000000n});const r=await client.waitForTransactionReceipt({hash:h});assert.equal(r.status,'success');};const id=hash('attack');await invoke('create',[id,bob,await now()+100],stake);await advance(101);await invoke('cancel',[id]);await invoke('withdraw');assert.equal(await client.getBalance({address:receiver}),stake);assert.equal(await read('claimable',[receiver]),0n);});
  await check('deterministic property sweep conserves every native unit',async()=>{for(let n=1;n<=12;n++){const value=BigInt(n*17+3)*1000000000000000n;const id=hash(`property-${n}`);await send(alice,'createChallenge',[id,bob,86400,await now()+100],value);await send(bob,'acceptChallenge',[id],value);await advance(86401);await send(oracle,'settleDuel',[id,n%3,hash(`r-${n}`)]);const locked=await read('totalLocked') as bigint,claimable=await read('totalClaimable') as bigint;assert.equal(await client.getBalance({address}),locked+claimable);if(await read('claimable',[alice]) as bigint)await send(alice,'claim');if(await read('claimable',[bob]) as bigint)await send(bob,'claim');}assert.equal(await client.getBalance({address}),0n);});
  console.log(`${count} EVM contract scenarios passed. No contracts deployed to a public network.`);
}finally{await provider.disconnect();}
export type ContractHash=Hex;
