// Local validator only. Run through `anchor test`, after installing the pinned toolchain.
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { randomBytes } from 'node:crypto';
import { AnchorProvider, BN, Program, type Idl } from '@coral-xyz/anchor';
import { Keypair, PublicKey, SystemProgram, Transaction } from '@solana/web3.js';
const provider=AnchorProvider.env();
if(!/^https?:\/\/(127\.0\.0\.1|localhost):/.test(provider.connection.rpcEndpoint))throw new Error('Escrow tests must use a local validator.');
const idl=JSON.parse(readFileSync('target/idl/duel_escrow.json','utf8')) as Idl;
const program=new Program(idl,provider),admin=provider.wallet.publicKey,opponent=Keypair.generate(),stranger=Keypair.generate();
const [config]=PublicKey.findProgramAddressSync([Buffer.from('config')],program.programId);
const [programData]=PublicKey.findProgramAddressSync([program.programId.toBuffer()],new PublicKey('BPFLoaderUpgradeab1e11111111111111111111111'));
await provider.sendAndConfirm(new Transaction().add(...[opponent,stranger].map(p=>SystemProgram.transfer({fromPubkey:admin,toPubkey:p.publicKey,lamports:50000000}))));
await program.methods.initialize(admin).accountsStrict({config,program:program.programId,programData,administrator:admin,systemProgram:SystemProgram.programId}).rpc();
await assert.rejects(program.methods.initialize(stranger.publicKey).accountsStrict({config,program:program.programId,programData,administrator:stranger.publicKey,systemProgram:SystemProgram.programId}).signers([stranger]).rpc());
const create=async(expirySeconds=3600)=>{
  const id=randomBytes(32),[duel]=PublicKey.findProgramAddressSync([Buffer.from('duel'),admin.toBuffer(),id],program.programId);
  const clock=await provider.connection.getBlockTime(await provider.connection.getSlot('confirmed'));
  await program.methods.createChallenge([...id],new BN(1000000),new BN(86400),new BN((clock??Math.floor(Date.now()/1000))+expirySeconds)).accountsStrict({config,duel,challenger:admin,opponent:opponent.publicKey,systemProgram:SystemProgram.programId}).rpc();
  return duel;
};
const duel=await create();
await assert.rejects(program.methods.acceptChallenge(new BN(1000000)).accountsStrict({config,duel,opponent:stranger.publicKey,systemProgram:SystemProgram.programId}).signers([stranger]).rpc());
await assert.rejects(program.methods.acceptChallenge(new BN(1)).accountsStrict({config,duel,opponent:opponent.publicKey,systemProgram:SystemProgram.programId}).signers([opponent]).rpc());
await program.methods.acceptChallenge(new BN(1000000)).accountsStrict({config,duel,opponent:opponent.publicKey,systemProgram:SystemProgram.programId}).signers([opponent]).rpc();
await assert.rejects(program.methods.acceptChallenge(new BN(1000000)).accountsStrict({config,duel,opponent:opponent.publicKey,systemProgram:SystemProgram.programId}).signers([opponent]).rpc());
const recipients={config,duel,challenger:admin,opponent:opponent.publicKey};
await assert.rejects(program.methods.settleDuel(1,[...randomBytes(32)]).accountsStrict({...recipients,authority:stranger.publicKey}).signers([stranger]).rpc());
await assert.rejects(program.methods.settleDuel(1,[...randomBytes(32)]).accountsStrict({...recipients,authority:admin}).rpc());
await assert.rejects(program.methods.refundDuel().accountsStrict({duel,participant:admin,challenger:admin,opponent:opponent.publicKey}).rpc());
await program.methods.setPaused(true).accountsStrict({config,administrator:admin}).rpc();
await assert.rejects(create());
await program.methods.setPaused(false).accountsStrict({config,administrator:admin}).rpc();
const expired=await create(3);await new Promise(r=>setTimeout(r,5000));
const before=await provider.connection.getBalance(expired);
await program.methods.cancelExpiredChallenge().accountsStrict({duel:expired,challenger:admin}).rpc();
assert.equal(before-await provider.connection.getBalance(expired),1000000);
await assert.rejects(program.methods.cancelExpiredChallenge().accountsStrict({duel:expired,challenger:admin}).rpc());
console.log('PASS local-validator initialization, deposits, authorization, duplicate acceptance, early settlement/refund guards, pause and expired refund. Time-warp settlement tests still required before deployment.');
