import { test, expect, type Page } from '@playwright/test';
const connect=async(page:Page,name:string)=>{await page.locator('.wallet-button').click();await page.getByRole('dialog').getByRole('button',{name:new RegExp(`^${name} `,'i')}).click();await expect(page.getByRole('dialog')).not.toBeVisible();};
test('arena, search, leaderboard, rules, and responsive layouts',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await expect(page.getByRole('heading',{name:/Big talk/})).toBeVisible();await expect(page.getByText('DEMO ARENA',{exact:false})).toBeVisible();await page.screenshot({path:'.data/qa-home-desktop.png',fullPage:true});
  await page.getByRole('navigation').getByRole('link',{name:'Explore',exact:true}).click();await page.getByRole('textbox',{name:'Search duels'}).fill('orangie');await expect(page.locator('.duel-card')).not.toHaveCount(0);await page.getByRole('textbox',{name:'Search duels'}).fill('no-such-duel-zzzz');await expect(page.getByRole('heading',{name:'No duels match.'})).toBeVisible();await page.getByRole('button',{name:'Clear filters'}).click();
  await page.goto('/leaderboard');await expect(page.getByRole('heading',{name:'All receipts. No hype.'})).toBeVisible();await page.getByRole('button',{name:'Win rate',exact:true}).click();await expect(page.locator('tbody tr')).toHaveCount(12);
  await page.goto('/d/GYRO7D');await expect(page.getByRole('heading',{name:'Portfolio performance'})).toBeVisible();await page.screenshot({path:'.data/qa-duel-desktop.png',fullPage:true});await page.getByRole('button',{name:'Show the calculation'}).click();await expect(page.getByText('Starting equity').first()).toBeVisible();
  await connect(page,'You');
  for(const width of [375,390,430,768]){await page.setViewportSize({width,height:844});for(const route of ['/','/explore','/d/GYRO7D','/challenge','/leaderboard','/setup']){await page.goto(route);await expect(page.locator('h1').first()).toBeVisible();const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);expect(overflow,`${route} overflows at ${width}px`).toBe(false);}if(width===390){await page.goto('/');await expect(page.getByRole('heading',{name:/Big talk/})).toBeVisible();await page.screenshot({path:'.data/qa-home-mobile.png',fullPage:true});}}
  expect(errors).toEqual([]);
});
test('create, wrong-wallet acceptance, correct acceptance, prediction, settlement and sharing',async({page})=>{
  await page.goto('/');await expect(page.getByRole('heading',{name:/Big talk/})).toBeVisible();await connect(page,'gyro');await page.goto('/challenge?opponent=@orangie&chain=solana');await expect(page.getByRole('heading',{name:'Call them out.'})).toBeVisible();await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Create challenge',exact:true}).click();await expect(page).toHaveURL(/\/challenge\/[A-Z0-9]+/);const duelPath=new URL(page.url()).pathname;await expect(page.getByRole('button',{name:'Share the callout'})).toBeVisible();
  const wrong=await page.evaluate(async()=>{const slug=location.pathname.split('/').at(-1);const r=await fetch(`/api/duels/${slug}`);const d=await r.json();const response=await fetch(`/api/duels/${d.duel.id}/accept`,{method:'POST',headers:{'Content-Type':'application/json','X-Duels-Request':'1'},body:'{}'});return response.status;});expect(wrong).toBe(403);
  await connect(page,'orangie');await page.goto(duelPath);await page.getByRole('button',{name:'Accept challenge',exact:true}).click();await expect(page.locator('.status-active')).toBeVisible();await connect(page,'You');await page.goto(duelPath);await page.getByRole('spinbutton',{name:'Prediction points'}).fill('100');await page.getByRole('button',{name:'Back gyro',exact:true}).click();await expect(page.getByText(/You backed gyro with 100 points/)).toBeVisible();
  await page.getByRole('button',{name:'Share duel',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download card'}).click();const file=await download;expect(file.suggestedFilename()).toMatch(/\.png$/);await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).not.toBeVisible();
  await page.getByRole('button',{name:'Finish demo duel'}).click();await expect(page.locator('.status-completed')).toBeVisible();await expect(page.locator('.winner-banner')).toBeVisible();await page.getByRole('button',{name:'Show the calculation'}).click();await expect(page.getByText('Reproducible result hash')).toBeVisible();await expect(page.getByText(/points returned/)).toBeVisible();
  await page.goto('/admin');await expect(page.getByRole('heading',{name:'Keep the arena running.'})).toBeVisible();await expect(page.getByText('No provider credits used.')).toBeVisible();
});
