[toolchain]
anchor_version = "0.32.1"
solana_version = "2.3.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
duel_escrow = "Fg6PaFpoGXkYsidMpWxTWqkZcM2Y8aVzWBfVvZo1qS5C"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec tsx ../../tests/contracts/solana.ts"
