import { createContext, useContext, useEffect, useState } from 'react';
import { Link, NavLink, Outlet, useLocation } from 'react-router-dom';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowRight, Bell, ChevronDown, Menu, Plus, Wallet, X } from 'lucide-react';
import { CHAINS } from '@shared/config';
import { linkedWallets } from '@shared/portfolio';
import type { DuelEvent } from '@shared/types';
import { api, nameOf, type Bootstrap } from './lib/api';
import { WalletOptions } from './components/wallet-options';
import { Avatar, ErrorPanel, Logo, Modal, Skeleton } from './components/ui';
type AppContextType={data:Bootstrap;connect:()=>void;toast:(text:string)=>void;refresh:()=>Promise<void>};
const AppContext=createContext<AppContextType|null>(null);
export function useApp(){const value=useContext(AppContext);if(!value)throw new Error('Application context missing');return value;}
export function AppLayout(){
  const query=useQuery({queryKey:['bootstrap'],queryFn:()=>api<Bootstrap>('/bootstrap'),refetchInterval:30000,retry:1});const client=useQueryClient();const [walletOpen,setWalletOpen]=useState(false);const [menuOpen,setMenuOpen]=useState(false);const [notifications,setNotifications]=useState(false);const [notice,setNotice]=useState('');const location=useLocation();
  const toast=(text:string)=>setNotice(text);useEffect(()=>{if(!notice)return;const timeout=setTimeout(()=>setNotice(''),4500);return()=>clearTimeout(timeout);},[notice]);
  useEffect(()=>{window.scrollTo({top:0});setMenuOpen(false);},[location.pathname]);
  const refresh=async()=>{await client.invalidateQueries();};
  if(query.isPending)return <Skeleton/>;if(query.error)return <div className="page"><Logo/><ErrorPanel error={query.error} retry={()=>void query.refetch()}/></div>;
  const data=query.data;return <AppContext.Provider value={{data,connect:()=>setWalletOpen(true),toast,refresh}}>
    <div className="mode-banner"><span className="mode-marker"/>{data.mode==='demo'?'DEMO ARENA':'Open beta'}<span className="banner-detail">{data.mode==='demo'?'Illustrative wallets. Simulated stakes. Real rivalry.':'Real rivalries. Simulated stakes. Points have no cash value.'}</span><Link to="/rules">Know the rules <ArrowRight size={12}/></Link></div>
    <header className="header"><div className="header-inner"><Link to="/" aria-label="PNL Duels home"><Logo/></Link><nav className={menuOpen?'nav open':'nav'} aria-label="Main navigation"><NavLink to="/" end>Arena</NavLink><NavLink to="/explore">Explore</NavLink><NavLink to="/leaderboard">Leaderboard</NavLink></nav><div className="header-actions"><button className="icon-button notification-button" aria-label="Notifications" onClick={()=>data.profile?setNotifications(true):setWalletOpen(true)}><Bell size={18}/></button><Link to="/challenge" className="button small-button header-create"><Plus size={15}/>Create duel</Link><button className="button wallet-button" onClick={()=>setWalletOpen(true)}>{data.profile?<><Avatar profile={data.profile} size={22}/><span>{nameOf(data.profile)}</span><ChevronDown size={13}/></>:<><Wallet size={15}/><span>Connect wallet</span></>}</button><button className="icon-button mobile-menu" onClick={()=>setMenuOpen(!menuOpen)} aria-label="Toggle menu" aria-expanded={menuOpen}>{menuOpen?<X size={20}/>:<Menu size={20}/>}</button></div></div></header>
    <main id="main"><Outlet/></main>
    <footer className="footer"><div><Link to="/"><Logo/></Link><p>Reputation is earned on the chart.</p></div><div className="footer-links"><Link to="/rules">Duel rules</Link><Link to="/setup">API setup</Link>{data.admin&&<Link to="/admin">System</Link>}<Link to="/terms">Terms</Link><Link to="/privacy">Privacy</Link></div><span className="footer-mode"><i className="live-dot"/>{data.mode==='demo'?'Demo environment':'Beta environment'}</span></footer>
    <WalletDialog open={walletOpen} setOpen={setWalletOpen}/><Notifications open={notifications} setOpen={setNotifications}/>
    {notice&&<div role="status" className="toast">{notice}<button className="icon-button" onClick={()=>setNotice('')} aria-label="Dismiss notification"><X size={14}/></button></div>}
  </AppContext.Provider>;
}
function WalletDialog({open,setOpen}:{open:boolean;setOpen:(v:boolean)=>void}){const {data,toast,refresh}=useApp();const [family,setFamily]=useState<'solana'|'evm'>('solana');const [busy,setBusy]=useState(false),[error,setError]=useState('');const run=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await fn();await refresh();setOpen(false);toast('You’re connected');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  return <Modal open={open} onOpenChange={value=>{if(!busy)setOpen(value);}} title={data.mode==='demo'?'Choose your corner.':data.profile?'Link your wallets.':'Connect your wallet.'} description={data.mode==='demo'?'Switch between demo traders to create challenges, accept them, and back a side. No wallet or funds required.':'Sign a one-time message to prove wallet ownership. No transaction or spending permission is requested.'}>
    {data.profile&&<div className="connected-wallet"><Avatar profile={data.profile}/><div><strong>{nameOf(data.profile)}</strong><small>{data.points?.toLocaleString()} duel points</small></div><button className="text-button" disabled={busy} onClick={()=>void run(()=>api('/auth/logout',{method:'POST',body:{}}))}>Disconnect</button></div>}
    {data.mode==='demo'?<div className="persona-grid">{data.traders.concat(data.traders.some(p=>p.id==='demo-you')?[]:[{id:'demo-you',wallet:'DemoYou1111111111111111111111111111111111111',username:'you',chain:'solana',createdAt:0,following:[],demo:true,stats:{wins:0,losses:0,ties:0,total:0,winRate:0,averageReturn:0,bestReturn:0,worstReturn:0,streak:0,longestStreak:0,won:0,staked:0}}]).map(p=><button key={p.id} className={`persona ${data.profile?.id===p.id?'selected':''}`} disabled={busy} onClick={()=>void run(()=>api('/auth/demo',{method:'POST',body:{profileId:p.id}}))}><Avatar profile={p} size={32}/><span><strong>{p.username==='you'?'You · spectator':nameOf(p)}</strong><small>{CHAINS[p.chain].name}</small></span></button>)}</div>:<><div className="wallet-coverage"><strong>One trader. All six chains.</strong><p>Link one Solana wallet and one EVM wallet. Your EVM address covers Base, BNB, Ethereum, Robinhood and Arc automatically.</p>{data.profile&&<ul>{linkedWallets(data.profile).map(w=><li key={w.family}>{w.family==='solana'?'Solana':'EVM'} linked: <code>{w.address.slice(0,6)}...{w.address.slice(-4)}</code></li>)}</ul>}</div><div className="duration-picker"><button className={family==='solana'?'selected':''} disabled={busy} onClick={()=>{setFamily('solana');setError('');}}>Solana wallet</button><button className={family==='evm'?'selected':''} disabled={busy} onClick={()=>{setFamily('evm');setError('');}}>EVM wallet</button></div>{data.profile&&linkedWallets(data.profile).some(w=>w.family===family)?<p className="notice-box">Your {family==='solana'?'Solana':'EVM'} wallet is linked. {linkedWallets(data.profile).length<2?'Link the other wallet to complete your portfolio.':'Both wallets are ready for portfolio inspection.'}</p>:<WalletOptions family={family} purpose={data.profile?'link':'login'} busy={busy} run={run}/>}{data.profile&&<Link className="text-button" to={`/trader/${data.profile.id}`} onClick={()=>setOpen(false)}>View your profile and portfolio <ArrowRight size={15}/></Link>}</>}
    {error&&<p className="form-error" role="alert">{error}</p>}<p className="dialog-footnote">{data.mode==='demo'?'Demo identities and their performance are illustrative.':'Your wallet remains in your control.'}</p>
  </Modal>;
}
function Notifications({open,setOpen}:{open:boolean;setOpen:(v:boolean)=>void}){const query=useQuery({queryKey:['notifications'],queryFn:()=>api<DuelEvent[]>('/notifications'),enabled:open});const {data}=useApp();return <Modal open={open} onOpenChange={setOpen} title="Your corner of the arena." description="Challenges and updates from traders you follow."><div className="notification-list">{query.data?.length?query.data.map(e=><Link onClick={()=>setOpen(false)} key={e.id} to={`/d/${data.duels.find(d=>d.id===e.duelId)?.slug??''}`}>{e.text}<ArrowRight size={14}/></Link>):<p className="muted">No updates yet. Follow a trader or start your first duel.</p>}</div></Modal>;}
