import { useEffect, useId, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowUpRight, Check, Clock3, Copy, Download, ExternalLink, ShieldCheck, Trophy, X } from 'lucide-react';
import * as Dialog from '@radix-ui/react-dialog';
import { CHAINS, PRODUCT, type Chain } from '@shared/config';
import type { Duel, DuelView, Profile, Snapshot } from '@shared/types';
import { duelChainLabel, duelStakeSymbol } from '@shared/portfolio';
import { nameOf, pct } from '../lib/api';
export function Logo(){return <span className="brand"><span className="brand-mark" aria-hidden="true">//</span>{PRODUCT.name}<span className="beta">BETA</span></span>;}
export function Avatar({profile,size=40}:{profile:Profile;size?:number}){const id=useId();const hash=profile.wallet.split('').reduce((a,c)=>(a*31+c.charCodeAt(0))>>>0,17);const hue=hash%360;const cells=Array.from({length:15},(_,i)=>Boolean((hash>>>i)&1));return <svg width={size} height={size} viewBox="0 0 40 40" className="avatar" role="img" aria-label={`${nameOf(profile)} identicon`}><defs><clipPath id={id}><rect width="40" height="40" rx="8"/></clipPath></defs><g clipPath={`url(#${id})`}><rect width="40" height="40" fill={`hsl(${hue} 22% 17%)`}/>{cells.flatMap((on,i)=>on?[<rect key={i} x={5+(i%3)*6} y={5+Math.floor(i/3)*6} width="6" height="6" fill={`hsl(${hue} 46% 69%)`}/>,i%3!==2?<rect key={`${i}r`} x={5+(4-i%3)*6} y={5+Math.floor(i/3)*6} width="6" height="6" fill={`hsl(${hue} 46% 69%)`}/>:null]:[])}</g></svg>;}
export function ChainBadge({chain}:{chain:Chain}){return <span className="chain-badge"><i style={{background:CHAINS[chain].color}}/>{CHAINS[chain].name}</span>;}
export function DuelChainBadge({duel}:{duel:Pick<Duel,'chain'|'chains'>}){return duel.chains?<span className="chain-badge" title={duel.chains.map(c=>CHAINS[c].name).join(', ')}><i style={{background:'#b5f567'}}/>{duelChainLabel(duel)}</span>:<ChainBadge chain={duel.chain}/>;}
export function StatusBadge({status}:{status:string}){return <span className={`status status-${status.toLowerCase()}`}>{status==='ACTIVE'&&<i className="live-dot"/>}{status==='ACTIVE'?'LIVE':status==='COMPLETED'?'FINAL':status.replaceAll('_',' ')}</span>;}
export function Countdown({end,serverTime,compact=false}:{end:number;serverTime?:number;compact?:boolean}){const offset=useMemo(()=>(serverTime??Date.now())-Date.now(),[serverTime]);const [now,setNow]=useState(Date.now());useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id);},[]);const seconds=Math.max(0,Math.floor((end-now-offset)/1000));const days=Math.floor(seconds/86400),hours=Math.floor(seconds%86400/3600),minutes=Math.floor(seconds%3600/60);return <span className="countdown">{seconds===0?'Awaiting finalization':compact?`${days?`${days}d `:''}${hours}h ${minutes}m`:`${days}D ${String(hours).padStart(2,'0')}H ${String(minutes).padStart(2,'0')}M ${String(seconds%60).padStart(2,'0')}S`}</span>;}
export function Return({value,large=false}:{value:number|undefined;large?:boolean}){return <span className={`return ${large?'return-large':''} ${value===undefined||value===0?'neutral':value>0?'positive':'negative'}`}>{pct(value)}</span>;}
export function Backing({duel}:{duel:DuelView}){const total=duel.backing[0]+duel.backing[1];const share=total?duel.backing[0]/total*100:50;return <div className="backing"><div className="backing-track"><span style={{width:`${share}%`}}/></div><div className="backing-labels"><span>{total?`${Math.round(share)}%`:'No predictions'}</span><span>{total?`${Math.round(100-share)}%`:''}</span></div></div>;}
export function DuelCard({duel}:{duel:DuelView}){return <Link to={`/d/${duel.slug}`} className="duel-card"><div className="card-top"><StatusBadge status={duel.status}/><DuelChainBadge duel={duel}/></div><div className="card-match"><div><Avatar profile={duel.challengerProfile}/><strong>{nameOf(duel.challengerProfile)}</strong><Return value={duel.challengerReturn}/></div><span className="vs">VS</span><div><Avatar profile={duel.opponentProfile}/><strong>{nameOf(duel.opponentProfile)}</strong><Return value={duel.opponentReturn}/></div></div><Backing duel={duel}/><div className="card-bottom"><span><Trophy size={13}/>{Number(duel.stake)*2} {duelStakeSymbol(duel)}<small>simulated pot</small></span><span><Clock3 size={13}/>{duel.endsAt?<Countdown end={duel.endsAt} compact/>:`${duel.duration/86400000} days`}</span><ArrowUpRight size={16}/></div></Link>;}
export function Empty({title,description,action}:{title:string;description:string;action?:React.ReactNode}){return <div className="empty"><span className="empty-icon">//</span><h3>{title}</h3><p>{description}</p>{action}</div>;}
export function Skeleton(){return <div className="page skeleton" aria-label="Loading page"><div className="skeleton-title"/><div className="skeleton-hero"/><div className="card-grid">{[0,1,2].map(i=><div key={i} className="skeleton-card"/>)}</div></div>;}
export function ErrorPanel({error,retry}:{error:Error;retry?:()=>void}){return <Empty title="We couldn’t load this." description={error.message} action={retry&&<button className="button" onClick={retry}>Try again</button>}/>;}
export function Modal({open,onOpenChange,title,description,children}:{open:boolean;onOpenChange:(open:boolean)=>void;title:string;description:string;children:React.ReactNode}){return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="dialog-content"><Dialog.Title>{title}</Dialog.Title><Dialog.Description>{description}</Dialog.Description><Dialog.Close className="icon-button dialog-close" aria-label="Close dialog"><X size={19}/></Dialog.Close>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>;}
export function ShareDialog({duel,open,onOpenChange,toast}:{duel:DuelView;open:boolean;onOpenChange:(v:boolean)=>void;toast:(s:string)=>void}){
  const url=`${location.origin}/d/${duel.slug}`;const text=`I'm calling out @${nameOf(duel.opponentProfile)}. ${duel.stake} ${duelStakeSymbol(duel)} each. ${duel.duration/86400000} days. Best portfolio return wins. ${duel.demo?'Demo duel. ':''}Simulated stakes.\nBack your trader ↓\n${url}`;
  const [copied,setCopied]=useState(false);const copy=async(value:string)=>{try{await navigator.clipboard.writeText(value);setCopied(true);toast('Copied to clipboard');}catch{toast('Copy is unavailable. Select the link below to copy it.');}};
  const download=async()=>{try{const response=await fetch(`/og/${duel.slug}.svg`);if(!response.ok)throw new Error('No share image');const blob=await response.blob();const image=new Image();const objectUrl=URL.createObjectURL(blob);image.src=objectUrl;await image.decode();const canvas=document.createElement('canvas');canvas.width=1200;canvas.height=630;canvas.getContext('2d')!.drawImage(image,0,0);URL.revokeObjectURL(objectUrl);const png=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,'image/png'));if(!png)throw new Error();const link=document.createElement('a');link.href=URL.createObjectURL(png);link.download=`duel-${duel.slug}.png`;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);toast('Share card downloaded');}catch{toast('Share card could not be generated. Try again.');}};
  return <Modal open={open} onOpenChange={onOpenChange} title="Make it public." description="A good rivalry deserves an audience."><div className="share-preview">{duel.visibility==='PUBLIC'?<img src={`/og/${duel.slug}.svg`} alt={`${nameOf(duel.challengerProfile)} versus ${nameOf(duel.opponentProfile)} share card`}/>:<p>This duel is unlisted. Only share the direct link with people you choose.</p>}</div><div className="share-buttons"><a className="button" target="_blank" rel="noreferrer" href={`https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}`}>Share on X <ArrowUpRight size={15}/></a><a className="button secondary" target="_blank" rel="noreferrer" href={`https://t.me/share/url?url=${encodeURIComponent(url)}&text=${encodeURIComponent(text.split('\n')[0])}`}>Telegram <ExternalLink size={14}/></a></div><div className="copy-field"><input aria-label="Duel share link" value={url} readOnly onFocus={e=>e.currentTarget.select()}/><button className="icon-button" onClick={()=>void copy(url)} aria-label="Copy link">{copied?<Check size={18}/>:<Copy size={18}/>}</button></div><div className="share-buttons"><button className="text-button" onClick={()=>void copy(text)}>Copy callout for Discord</button>{duel.visibility==='PUBLIC'&&<button className="text-button" onClick={()=>void download()}><Download size={14}/>Download card</button>}</div></Modal>;
}
export function Quality({quality,issues}:{quality:string;issues:string[]}){return <span className={`quality quality-${quality.toLowerCase()}`} title={issues.length?issues.join('; '):'Valuation and transaction coverage checks passed for the available evidence.'}><ShieldCheck size={13}/>{quality.toLowerCase()} data quality</span>;}
export function Portfolio({snapshot}:{snapshot?:Snapshot}){if(!snapshot)return <p className="muted small">Positions appear after the starting snapshot is recorded.</p>;const sum=Number(snapshot.totalUsd);return <div className="positions">{snapshot.components&&<><div className="portfolio-total"><span>{snapshot.quality==='INCOMPLETE'?'Eligible equity (partial)':'Combined eligible equity'}</span><strong>{sum.toLocaleString('en-US',{style:'currency',currency:'USD'})}</strong></div><div className="chain-coverage">{snapshot.components.map(part=><div key={part.chain}><ChainBadge chain={part.chain}/><span className={part.quality==='INCOMPLETE'?'coverage-incomplete':''}>{part.block==='unavailable'?'Unavailable':part.quality==='INCOMPLETE'?'Needs evidence':Number(part.totalUsd).toLocaleString('en-US',{style:'currency',currency:'USD'})}</span></div>)}</div></>}{snapshot.positions.map(p=><div className="position-row" key={`${p.chain??snapshot.chain}:${p.address}`}><span className="token-icon">{p.symbol.slice(0,1)}</span><div><strong>{p.symbol}{p.chain&&<span className="position-chain"> {CHAINS[p.chain].name}</span>}</strong><small title={p.reason}>{p.reason||`${Number(p.balance).toLocaleString(undefined,{maximumFractionDigits:4})} tokens`}</small></div><div className="position-value"><strong>{Number(p.valueUsd).toLocaleString('en-US',{style:'currency',currency:'USD'})}</strong><small>{sum?(Number(p.valueUsd)/sum*100).toFixed(1):'0'}%</small></div></div>)}</div>;}
