import { duelStakeSymbol } from '@shared/portfolio';
import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { ArrowLeft, ArrowUpRight, Check, ChevronDown, Clock3, ExternalLink, Flag, Play, Share2, ShieldCheck, Trophy } from 'lucide-react';
import { CHAINS, RULES } from '@shared/config';
import { useApp } from '../app';
import { Avatar, Backing, DuelChainBadge, Countdown, ErrorPanel, Portfolio, Quality, Return, ShareDialog, Skeleton, StatusBadge } from '../components/ui';
import { PerformanceChart } from '../components/chart';
import { age, api, money, nameOf, short, type DuelDetail } from '../lib/api';
export default function DuelPage(){const {slug}=useParams();const {data,connect,toast,refresh}=useApp();const query=useQuery({queryKey:['duel',slug],queryFn:()=>api<DuelDetail>(`/duels/${slug}`),refetchInterval:q=>q.state.data?.duel.status==='COMPLETED'?false:15000});const [share,setShare]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[tab,setTab]=useState('portfolio'),[points,setPoints]=useState(100),[calculation,setCalculation]=useState(false);
  if(query.isPending)return <Skeleton/>;if(query.error)return <ErrorPanel error={query.error} retry={()=>void query.refetch()}/>;
  const {duel:d,snapshots,events,flows,predictions,transactions,serverTime}=query.data;const latest=[d.challenger,d.opponent].map(wallet=>snapshots.filter(s=>s.wallet===wallet).sort((a,b)=>b.timestamp-a.timestamp)[0]);const leader=(d.challengerReturn??0)>=(d.opponentReturn??0)?d.challengerProfile:d.opponentProfile;const lead=Math.abs((d.challengerReturn??0)-(d.opponentReturn??0));const isParticipant=data.profile&&[d.challenger,d.opponent].includes(data.profile.id);const cutoff=d.startsAt!+d.duration*RULES.predictionCutoffFraction;const canPredict=d.status==='ACTIVE'&&serverTime<cutoff&&!isParticipant&&!predictions.length;
  const run=async(path:string,body:unknown={})=>{setBusy(true);setError('');try{await api(path,{method:'POST',body});await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  return <div className="page duel-page"><div className="breadcrumbs"><Link to="/explore"><ArrowLeft size={14}/>The arena</Link><span>/</span><span>{d.slug}</span><span className="breadcrumb-right"><Quality quality={d.quality} issues={d.issues}/><button className="text-button" onClick={()=>setShare(true)}><Share2 size={15}/>Share duel</button></span></div>
    <div className="duel-headline"><div><StatusBadge status={d.status}/><DuelChainBadge duel={d}/>{d.demo&&<span className="demo-label">DEMO</span>}</div><span>{d.status==='OPEN'?"YOU’VE BEEN CALLED OUT":d.status==='COMPLETED'?'THE NUMBERS HAVE SPOKEN':d.endsAt?<Countdown end={d.endsAt} serverTime={serverTime}/>:'CHALLENGE CREATED'}</span></div>
    {d.status==='COMPLETED'&&<div className="winner-banner"><Trophy size={22}/>{d.winner?`${nameOf(d.winner===d.challenger?d.challengerProfile:d.opponentProfile)} wins.`:'Evenly matched. It’s a tie.'}<span>Final result</span></div>}
    <section className="duel-matchup panel">{[d.challengerProfile,d.opponentProfile].map((p,i)=><div className={`participant participant-${i}`} key={p.id}><Link to={`/trader/${p.id}`} className="participant-name"><Avatar profile={p} size={56}/><span><h1>{nameOf(p)}</h1><small>{(i?d.opponentStats:d.challengerStats).wins} W <span>·</span> {(i?d.opponentStats:d.challengerStats).losses} L <span>·</span> {short(p.wallet)}</small></span><ArrowUpRight size={15}/></Link><Return value={i?d.opponentReturn:d.challengerReturn} large/><p className="equity">{latest[i]?money(latest[i].totalUsd):'Starting snapshot pending'}<span>portfolio value</span></p></div>)}<span className="duel-vs">VS</span><div className="lead-strip">{d.status==='OPEN'?<><Flag size={13}/>{d.duration/86400000} days. Best adjusted return wins.</>:d.quality==='INCOMPLETE'?<><ShieldCheck size={13}/>Performance pending complete evidence</>:<><span className="live-dot"/>{d.status==='COMPLETED'?'Final margin':`${nameOf(leader)} leads`}<strong>{lead.toFixed(2)} percentage points</strong></>}</div></section>
    <div className="duel-meta"><div><Trophy size={16}/><span><strong>{Number(d.stake)*2} {duelStakeSymbol(d)}</strong><small>Simulated pot · {d.stake} each</small></span></div><div><Clock3 size={16}/><span><strong>{d.duration/86400000} days</strong><small>Competition duration</small></span></div><div><ShieldCheck size={16}/><span><strong>Cash-flow adjusted</strong><small>Rules {d.rulesVersion}</small></span></div><div><span className="live-dot"/><span><strong>{d.lastUpdated?age(d.lastUpdated):'Not started'}</strong><small>Last snapshot</small></span></div></div>
    {d.status==='OPEN'&&<section className="accept-panel panel"><div><h2>Back up the big talk.</h2><p>This challenge is for <strong>{nameOf(d.opponentProfile)}</strong>. It expires <Countdown end={d.expiresAt} compact/> from now.</p></div><div>{!data.profile?<button className="button primary" onClick={connect}>Connect wallet to accept</button>:data.profile.id===d.opponent?<><button className="button primary" disabled={busy} onClick={()=>void run(`/duels/${d.id}/accept`)}>{busy?'Recording portfolios…':'Accept challenge'}<Check size={16}/></button><button className="text-button" disabled={busy} onClick={()=>void run(`/duels/${d.id}/cancel`)}>Decline</button></>:data.profile.id===d.challenger?<><button className="button primary" onClick={()=>setShare(true)}>Share the callout <Share2 size={16}/></button><button className="text-button" onClick={()=>void run(`/duels/${d.id}/cancel`)}>Cancel challenge</button></>:<p className="muted">Only {short(d.opponentProfile.wallet)} can accept.<br/><button className="text-button" onClick={connect}>Switch wallet <ArrowUpRight size={14}/></button></p>}</div></section>}
    {error&&<p className="notice-box error" role="alert">{error}</p>}{!!d.issues.length&&<div className="notice-box warning"><strong>Data needs review.</strong> {d.issues.join(' ')} No winner will be declared from incomplete data.</div>}
    <div className="duel-content"><div className="duel-main"><section className="panel chart-panel"><div className="panel-heading"><div><h3>Portfolio performance</h3></div><span className="eyebrow">RETURN %</span></div><PerformanceChart duel={d} snapshots={snapshots}/></section><section className="panel portfolio-panel"><div className="panel-tabs">{['portfolio','activity','transactions'].map(v=><button key={v} className={tab===v?'active':''} onClick={()=>setTab(v)}>{v[0].toUpperCase()+v.slice(1)}</button>)}</div>{tab==='portfolio'?<div className="portfolio-columns">{[d.challengerProfile,d.opponentProfile].map((p,i)=><div key={p.id}><h4><Avatar profile={p} size={22}/>{nameOf(p)}</h4><Portfolio snapshot={latest[i]}/></div>)}</div>:tab==='activity'?<div className="duel-activity">{events.map(e=><div key={e.id}><span className="activity-mark"><Flag size={15}/></span><p>{e.text}<small>{new Date(e.createdAt).toLocaleString()}</small></p></div>)}</div>:<div className="transactions">{transactions.length?transactions.map(tx=><a key={tx.id} href={`${CHAINS[tx.chain].explorer}/tx/${tx.hash}`} target="_blank" rel="noreferrer"><span><strong>{tx.classification.replaceAll('_',' ')}</strong><small>{tx.reason}</small></span><code>{short(tx.hash)}</code><ExternalLink size={14}/></a>):<p className="panel-empty">{d.demo?'Demo charts use deterministic portfolio fixtures. No fabricated transactions are shown.':'No indexed wallet transactions in this duel yet.'}</p>}</div>}</section>
    <section className="transparency panel"><button onClick={()=>setCalculation(!calculation)} aria-expanded={calculation}><span><ShieldCheck size={17}/><strong>Show the calculation</strong></span><ChevronDown size={17} className={calculation?'rotated':''}/></button>{calculation&&<div className="calculation-body"><p>Returns are compounded between external cash flows. Trading fees and gas reduce performance. Stakes are simulated and no assets move.</p><div className="calculation-grid">{[d.challengerProfile,d.opponentProfile].map((p,i)=>{const first=snapshots.filter(s=>s.wallet===p.id).sort((a,b)=>a.timestamp-b.timestamp)[0];return <div key={p.id}><h4>{nameOf(p)}</h4><dl><dt>Starting equity</dt><dd>{first?money(first.totalUsd):'Pending'}</dd><dt>Latest equity</dt><dd>{latest[i]?money(latest[i].totalUsd):'Pending'}</dd><dt>External flows</dt><dd>{money(flows.filter(f=>f.wallet===p.id).reduce((n,f)=>n+Number(f.amountUsd),0))}</dd><dt>Block / slot</dt><dd>{latest[i]?.block??'Pending'}</dd></dl></div>;})}</div>{d.resultHash&&<div className="hash"><strong>Reproducible result hash</strong><code>{d.resultHash}</code></div>}<Link to="/rules" className="text-button">Read the full methodology <ArrowUpRight size={14}/></Link></div>}</section></div>
    <aside className="duel-sidebar"><section className="panel prediction-panel"><span className="eyebrow">PICK YOUR SIDE</span><h2>Who takes it?</h2><p>Back your trader with duel points.</p><div className="prediction-labels"><span>{nameOf(d.challengerProfile)}</span><span>{nameOf(d.opponentProfile)}</span></div><Backing duel={d}/><p className="prediction-count">{d.predictionCount} predictions · community backing</p>{data.profile&&<div className="point-balance"><span>Your balance</span><strong>{data.points?.toLocaleString()} <small>PTS</small></strong></div>}{canPredict?<><label className="field">Your prediction<input type="number" aria-label="Prediction points" min={10} max={10000} step={10} value={points} onChange={e=>setPoints(Number(e.target.value))}/></label><div className="prediction-buttons">{[d.challengerProfile,d.opponentProfile].map((p,i)=><button key={p.id} className={`button ${i?'secondary':'primary'}`} disabled={busy} onClick={()=>data.profile?void run(`/duels/${d.id}/predict`,{side:p.id,points}):connect()}>Back {nameOf(p)}</button>)}</div></>:<div className="prediction-closed">{predictions.length?<><Check size={16}/>You backed {nameOf(predictions[0].side===d.challenger?d.challengerProfile:d.opponentProfile)} with {predictions[0].points} points.{predictions[0].payout!==undefined&&<strong>{predictions[0].payout} points returned</strong>}</>:isParticipant?'Participants can’t predict their own duel.':d.status==='OPEN'?'Predictions open when the duel starts.':'Predictions are closed.'}</div>}<small className="points-disclaimer">Points have no cash value. Predictions close after {Math.round(RULES.predictionCutoffFraction*100)}% of the duel.</small></section>
    <section className="panel duel-share"><Share2 size={21}/><h3>A rivalry worth sharing.</h3><p>Bring your corner of the internet.</p><button className="button secondary full" onClick={()=>setShare(true)}>Share this duel <ArrowUpRight size={15}/></button></section>{d.status==='COMPLETED'&&<Link className="button primary full" to={`/challenge?opponent=${encodeURIComponent('@'+nameOf(d.opponentProfile))}&chain=${d.chain}&stake=${d.stake}&duration=${d.duration}`}>Run it back <ArrowUpRight size={16}/></Link>}{d.demo&&d.status==='ACTIVE'&&<div className="demo-controls"><strong>Try the full demo</strong><p>Advance to the finish to see the final calculation and points settlement.</p><button className="text-button" disabled={busy} onClick={()=>data.profile?void run(`/demo/finish/${d.id}`):connect()}><Play size={13}/>Finish demo duel</button></div>}</aside></div>
    <ShareDialog duel={d} open={share} onOpenChange={setShare} toast={toast}/>
  </div>;
}
