import { useMemo, useState } from 'react';
import { useLocation, useSearchParams, Link } from 'react-router-dom';
import { Search, SlidersHorizontal, Plus } from 'lucide-react';
import { useApp } from '../app';
import { DuelCard, Empty } from '../components/ui';
import { CHAINS } from '@shared/config';
import { nameOf } from '../lib/api';
export default function Explore(){const {data}=useApp();const location=useLocation();const [params]=useSearchParams();const [status,setStatus]=useState(params.get('status')??(location.pathname==='/live'?'ACTIVE':'ALL'));const [chain,setChain]=useState('all');const [search,setSearch]=useState('');const [duration,setDuration]=useState('all');const [sort,setSort]=useState('newest');const [limit,setLimit]=useState(12);
  const duels=useMemo(()=>data.duels.filter(d=>(status==='ALL'||status==='TRENDING'||d.status===status)&&(chain==='all'||(d.chains??[d.chain]).some(c=>c===chain))&&(duration==='all'||d.duration===Number(duration))&&`${nameOf(d.challengerProfile)} ${nameOf(d.opponentProfile)} ${d.challengerProfile.wallet} ${d.opponentProfile.wallet} ${d.slug}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>status==='TRENDING'?b.predictionCount-a.predictionCount:sort==='stake'?Number(b.stake)-Number(a.stake):b.createdAt-a.createdAt),[data.duels,status,chain,duration,search,sort]);
  return <div className="page"><div className="page-heading"><div><span className="eyebrow">PICK A RIVALRY</span><h1>The arena.</h1><p>Find your next duel. Follow the ones worth watching.</p></div><Link to="/challenge" className="button primary"><Plus size={16}/>Create duel</Link></div><div className="explore-tabs">{[['ALL','All duels'],['ACTIVE','Live'],['OPEN','Open challenges'],['COMPLETED','Completed'],['TRENDING','Trending']].map(([v,label])=><button key={v} onClick={()=>{setStatus(v);setLimit(12);}} className={status===v?'active':''}>{v==='ACTIVE'&&<i className="live-dot"/>}{label}</button>)}</div><div className="filters"><div className="search-field"><Search size={17}/><input aria-label="Search duels" placeholder="Search trader, wallet, or duel ID" value={search} onChange={e=>setSearch(e.target.value)}/></div><SlidersHorizontal size={16} className="filter-icon"/><select aria-label="Filter by chain" value={chain} onChange={e=>setChain(e.target.value)}><option value="all">All chains</option>{data.chains.map(c=><option key={c} value={c}>{CHAINS[c].name}</option>)}</select><select aria-label="Filter by duration" value={duration} onChange={e=>setDuration(e.target.value)}><option value="all">All durations</option><option value="86400000">24 hours</option><option value="259200000">3 days</option><option value="604800000">7 days</option></select><select aria-label="Sort duels" value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Newest first</option><option value="stake">Highest simulated stake</option></select></div><p className="results-count">{duels.length} duels {data.mode==='demo'?'· demo data':''}</p>{duels.length?<><div className="card-grid">{duels.slice(0,limit).map(d=><DuelCard key={d.id} duel={d}/>)}</div>{duels.length>limit&&<button className="button secondary load-more" onClick={()=>setLimit(limit+12)}>Load more duels</button>}</>:<Empty title="No duels match." description="Try a different chain or clear your search." action={<button className="button secondary" onClick={()=>{setSearch('');setChain('all');setDuration('all');setStatus('ALL');}}>Clear filters</button>}/>}</div>;
}
