import { duelStakeSymbol } from '@shared/portfolio';
import { Link } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { ArrowDown, ArrowRight, ArrowUpRight, ChartNoAxesCombined, ChevronRight, Crosshair, ShieldCheck, Swords, Trophy } from 'lucide-react';
import { useApp } from '../app';
import { Avatar, ChainBadge, DuelChainBadge, Countdown, DuelCard, Empty, Return, StatusBadge } from '../components/ui';
import { PerformanceChart } from '../components/chart';
import { api, age, compact, nameOf, type DuelDetail } from '../lib/api';
import { CHAINS } from '@shared/config';
export default function Home(){const {data}=useApp();const live=data.duels.filter(d=>d.status==='ACTIVE');const featured=live.find(d=>d.slug==='GYRO7D')??live[0];const detail=useQuery({queryKey:['duel',featured?.slug],queryFn:()=>api<DuelDetail>(`/duels/${featured!.slug}`),enabled:!!featured,refetchInterval:30000});const top=data.traders.filter(p=>p.stats.total>0).slice(0,5);const completed=data.duels.filter(d=>d.status==='COMPLETED').slice(0,3);
  return <div className="page home-page"><section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="line-label"/>THE ON-CHAIN TRADING ARENA</div><h1>Big talk.<br/><span>Prove it.</span></h1><p>Two wallets. Seven days. One winner.<br/>Challenge a trader and let your returns settle it.</p><div className="hero-buttons"><Link to="/challenge" className="button primary">Call them out <ArrowUpRight size={18}/></Link><a href="#arena" className="text-button">Enter the arena <ArrowDown size={15}/></a></div><div className="hero-trust"><span><ShieldCheck size={14}/>Cash-flow adjusted</span><span><ChartNoAxesCombined size={14}/>Wallet-level performance</span></div></div>
  {featured?<div className="featured"><div className="featured-header"><span><i className="live-dot"/>IN THE SPOTLIGHT</span><DuelChainBadge duel={featured}/></div><Link to={`/d/${featured.slug}`} className="featured-match"><div><div className="featured-trader"><Avatar profile={featured.challengerProfile} size={42}/><span><strong>{nameOf(featured.challengerProfile)}</strong><small>{featured.challengerStats.wins}W · {featured.challengerStats.losses}L</small></span></div><Return value={featured.challengerReturn} large/></div><span className="featured-vs">VS</span><div><div className="featured-trader"><span><strong>{nameOf(featured.opponentProfile)}</strong><small>{featured.opponentStats.wins}W · {featured.opponentStats.losses}L</small></span><Avatar profile={featured.opponentProfile} size={42}/></div><Return value={featured.opponentReturn} large/></div></Link><div className="hero-chart">{detail.data?<PerformanceChart duel={featured} snapshots={detail.data.snapshots} mini/>:<div className="skeleton-card"/>}</div><div className="featured-footer"><span><Trophy size={14}/><strong>{Number(featured.stake)*2} {duelStakeSymbol(featured)}</strong><small>simulated pot</small></span><span><Countdown end={featured.endsAt!} compact/></span><Link to={`/d/${featured.slug}`}>Watch duel <ArrowUpRight size={14}/></Link></div></div>:<div className="featured empty-feature"><Crosshair size={40}/><h2>The arena is yours.</h2><p>Create the first rivalry.</p><Link to="/challenge" className="button primary">Start a duel <ArrowRight size={16}/></Link></div>}
  </section>
  <div className="arena-statline"><div><span className="live-dot"/><strong>{live.length}</strong>live duels</div><div><strong>{data.traders.length}</strong>traders in the arena</div><div><strong>{compact(data.duels.reduce((sum,d)=>sum+d.predictionCount,0))}</strong>predictions placed</div><div className="statline-caption">THE NUMBERS DO THE TALKING.<span>NO EXCUSES.</span></div></div>
  <section id="arena" className="arena-section"><div className="section-heading"><div><div className="eyebrow">THE CLOCK IS RUNNING</div><h2>Live in the arena <span className="count-tag">{live.length}</span></h2></div><Link to="/live" className="text-button">View all duels <ArrowUpRight size={15}/></Link></div>{live.length?<div className="card-grid">{live.slice(0,6).map(d=><DuelCard key={d.id} duel={d}/>)}</div>:<Empty title="No live duels. Yet." description="A rivalry starts with one callout." action={<Link className="button primary" to="/challenge">Start a duel</Link>}/>}</section>
  <section className="home-bottom"><div className="leaderboard-panel panel"><div className="panel-heading"><div><Trophy size={16}/><h3>Traders to beat</h3></div><Link to="/leaderboard" className="icon-button" aria-label="View leaderboard"><ArrowUpRight size={18}/></Link></div><div className="leaderboard-labels"><span>TRADER</span><span>WIN RATE</span><span>AVG. RETURN</span></div>{top.length?top.map((p,i)=><Link key={p.id} to={`/trader/${p.id}`} className="leader-row"><span className="rank">{String(i+1).padStart(2,'0')}</span><Avatar profile={p} size={34}/><div className="leader-name"><strong>{nameOf(p)}</strong><small>{p.stats.wins} wins · {CHAINS[p.chain].name}</small></div><span>{p.stats.winRate.toFixed(0)}%</span><Return value={p.stats.averageReturn}/></Link>):<p className="panel-empty">Rankings begin when duels finish.</p>}</div>
  <div className="activity-panel panel"><div className="panel-heading"><div><Swords size={16}/><h3>From the arena</h3></div><span className="eyebrow">LATEST CALLOUTS</span></div>{data.events.length?data.events.slice(0,5).map(e=><Link key={e.id} className="activity-item" to={`/d/${data.duels.find(d=>d.id===e.duelId)?.slug??''}`}><span className="activity-mark"><ArrowUpRight size={17}/></span><div><p>{e.text}</p><small>{age(e.createdAt)}</small></div><ChevronRight size={15}/></Link>):<p className="panel-empty">The next callout could be yours.</p>}</div></section>
  {!!completed.length&&<section className="recent-results"><div className="section-heading"><h2>The numbers have spoken.</h2><Link to="/explore?status=COMPLETED" className="text-button">Final results <ArrowRight size={15}/></Link></div><div className="results-strip">{completed.map(d=><Link key={d.id} to={`/d/${d.slug}`}><StatusBadge status="COMPLETED"/><strong>{d.winner?nameOf(d.winner===d.challenger?d.challengerProfile:d.opponentProfile):'Tie'}</strong><span>{d.winner?'takes the duel':'Stakes returned'}</span><Return value={d.winner===d.challenger?d.challengerReturn:d.opponentReturn}/><ArrowUpRight size={16}/></Link>)}</div></section>}
  <section className="how-it-works"><div><span className="eyebrow">A SIMPLE WAY TO SETTLE IT</span><h2>Reputation.<br/>With receipts.</h2></div>{[{icon:Crosshair,title:'Pick your rival.',text:'Same chain. Same stake. Call out a wallet and share the challenge.'},{icon:ChartNoAxesCombined,title:'Trade your game.',text:'Your own wallet, your own strategy. Deposits and withdrawals are neutralized.'},{icon:Trophy,title:'Let the chart decide.',text:'The best adjusted return wins. A bigger wallet doesn’t get a head start.'}].map(({icon:Icon,title,text})=><div key={title} className="how-step"><Icon size={21}/><h3>{title}</h3><p>{text}</p></div>)}</section>
  <div className="chain-footer"><span>ONE ARENA. ALL CHAINS.</span>{data.chains.map(c=><ChainBadge key={c} chain={c}/>)}<Link to="/challenge">Your move <ArrowUpRight size={15}/></Link></div>
  </div>;
}
