import { Link, useLocation } from 'react-router-dom';
import { ArrowUpRight, BookOpen, Check, ChevronDown, ShieldCheck } from 'lucide-react';
import { RULES } from '@shared/config';
export default function Info(){const path=useLocation().pathname;if(path==='/setup')return <Setup/>;if(path==='/terms'||path==='/privacy')return <Legal privacy={path==='/privacy'}/>;
  return <div className="page info-page"><span className="eyebrow">THE RULEBOOK · {RULES.version}</span><h1>Better returns.<br/>A fair fight.</h1><p className="info-intro">Depositing more money doesn’t improve your score. Your duel measures the percentage return your portfolio generates, with external deposits and withdrawals removed from the equation.</p><div className="rule-highlight"><ShieldCheck size={27}/><div><strong>A bigger wallet doesn’t get a head start.</strong><p>A $1,000 portfolio that grows to $1,200 beats a $10,000 portfolio that grows to $11,000. +20% beats +10%.</p></div></div>{[
    ['Your starting line','Both participants link one Solana and one EVM wallet. New duels combine their equity across Solana, Base, BNB, Ethereum, Robinhood and Arc in USD, with the same duration and simulated stake. Wallet addresses and networks are locked at the start. The duel starts after both portfolios have usable starting snapshots. Each combined portfolio needs at least $10 in eligible equity and complete evidence on every included chain. Your tokens stay in your wallet.'],
    ['Deposits, withdrawals & airdrops','External transfers are neutralized using valuations immediately before and after the flow. Sending $10,000 into a $1,000 wallet does not create +1,000% performance. Swaps are not external flows when their classification is supported and verified. Ambiguous transfers pause scoring.'],
    ['Trading fees count','Gas and exchange fees reduce your equity. The duel measures the outcome of your trading, including what it costs to execute it.'],
    ['Prices need evidence','Tokens are identified by chain and address, never ticker alone. We select liquid reference pools, compare prices when possible, and record sources and timestamps. Missing prices are disclosed. Arc native USDC and its ERC-20 interface count as one asset. Historical performance is never reconstructed using today’s prices.'],
    ['Small pools, conservative values','Positions below $1 are dust. Pools require at least $10,000 in liquidity. A position below 2% of pool liquidity receives full eligible value, 2–10% receives a 10% haircut, and 10–25% receives a 50% haircut. Above 25%, it is excluded. New pools and conflicting prices are flagged. These rules reduce manipulation; they do not guarantee executable prices.'],
    ['Winning, ties & finalization','Highest time-weighted return wins. A difference of 0.05 percentage points or less is a tie. The backend reconciles transactions and ending snapshots before publishing the result. The final observation must fall within five minutes of the duel boundary. Missing coverage or failed integrity checks put a duel in review. A countdown reaching zero is not a final result.'],
    ['Pick a side with points','Every connected profile receives 10,000 duel points. A spectator can back one side once per duel; participants cannot back themselves. Predictions close after 80% of the duel duration. Winners split the total points pool in proportion to their stake. Ties, cancellations, or a pool without winning predictions refund the points. Points have no cash value.'],
    ['Beta means beta','Stakes are simulated. No mainnet funds are escrowed by this app. Demo wallets and returns are explicitly labeled. Live analytics are based on the on-chain and market evidence available to the indexer. Supported transfers and decoded swaps are replayed across the combined portfolio. Unknown contracts, bridges, missing historical prices and incomplete chain evidence pause settlement. Final results wait for canonical chain finality.'],
  ].map(([title,text],i)=><section className="rule-section" key={title}><span>{String(i+1).padStart(2,'0')}</span><div><h2>{title}</h2><p>{text}</p></div></section>)}<details className="technical-method"><summary><BookOpen size={17}/>Technical methodology<ChevronDown size={16}/></summary><p>For each external flow, close the preceding period at the pre-flow equity. Begin the next period at post-flow equity. Compound each period’s gross return:</p><code>TWR = ∏(end equity ÷ start equity) − 1</code><p>Amounts use decimal arithmetic. Snapshots are append-only. Every duel stores its rules version. Final calculation inputs are serialized in a stable order and hashed with SHA-256. A reproducible hash proves the recorded inputs are consistent; it does not certify an independent oracle audit.</p></details><Link to="/challenge" className="button primary">Ready to prove it? <ArrowUpRight size={17}/></Link></div>;
}
const providers=[
  {name:'Helius',label:'Solana RPC',key:'HELIUS_API_KEY',url:'https://dashboard.helius.dev',text:'Create an account, keep the Free plan, create a project, and copy its API key. Standard JSON-RPC is the primary path. Configure 900,000 app credits to leave headroom against the published 1M monthly allowance.'},
  {name:'Alchemy',label:'EVM RPC & token discovery',key:'ALCHEMY_API_KEY',url:'https://dashboard.alchemy.com',text:'Create a Free app and enable Ethereum, Base, BNB and Arc mainnet where available. Copy the API key. Its 30M monthly compute units are weighted by method; they are not 30M requests. Robinhood also has independent public RPC backups.'},
  {name:'Supabase',label:'Persistent database',key:'SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY',url:'https://supabase.com/dashboard',text:'Create a Free project. Run all three files in supabase/migrations in order in the SQL editor. Copy the project URL and server service-role key to the server environment. Use a separate project for live mode.'},
  {name:'Jupiter',label:'Solana price cross-check',key:'JUPITER_API_KEY',url:'https://portal.jup.ag',text:'Create a free API key. The published free plan allows 1 request/second; keyless access is lower. The app batches addresses and uses Jupiter to cross-check token prices.'},
  {name:'DexPaprika',label:'Market-data backup',key:'DEXPAPRIKA_API_KEY',url:'https://console.dexpaprika.com',text:'Register for a free key: the published allowance is 300K credits in a rolling 30-day window. No key is needed for the smaller 50K allowance. The app uses only the free API host.'},
  {name:'GMGN',label:'Optional memecoin market context',key:'GMGN_API_KEY + GMGN_FREE_ACCESS_CONFIRMED',url:'https://gmgn.ai/ai',text:'Run pnpm gmgn:keygen to create a local Ed25519 key pair. Submit only the public key in GMGN’s API form. Add your own API key and confirm that its read-only entitlement is free before enabling it. Public demo keys are not used in production. No swap or trading authority is needed.'},
  {name:'Cloudflare',label:'Hosting & scheduled updates',key:'Worker secrets',url:'https://dash.cloudflare.com',text:'Use Workers Free. Set server secrets with pnpm exec wrangler secret put NAME. Set APP_ORIGIN to the final HTTPS site address. Build, dry-run, and deploy using the documented commands.'},
];
function Setup(){return <div className="page setup-page"><div className="page-heading"><div><span className="eyebrow">YOUR MORNING CHECKLIST</span><h1>Keys in. Arena on.</h1><p>The demo already runs. These are the accounts and keys for live wallet data.</p></div><span className="setup-label"><Check size={16}/>Free-first setup</span></div><div className="setup-notice"><ShieldCheck size={22}/><div><strong>DEX Screener, GeckoTerminal, and public RPC backups need no API key.</strong><p>Keys belong in the server environment. Never put them in a VITE_ variable, commit them, or paste them into the app.</p></div></div><div className="setup-grid">{providers.map((p,i)=><section className="panel setup-card" key={p.name}><div className="setup-card-top"><span>{String(i+1).padStart(2,'0')}</span><span>{p.label}</span></div><h2>{p.name}</h2><p>{p.text}</p><code>{p.key}</code><a href={p.url} target="_blank" rel="noreferrer" className="text-button">Open {p.name} <ArrowUpRight size={15}/></a></section>)}</div><section className="setup-final panel"><h2>Switch to live data.</h2><ol><li>Copy <code>.env.example</code> to <code>.env</code>, then add your server keys.</li><li>Set a random <code>SESSION_SECRET</code> of at least 32 characters and your <code>ADMIN_WALLETS</code>.</li><li>Use a fresh database for live data and run the migrations.</li><li>Set <code>DEMO_MODE=false</code> and keep <code>REAL_MONEY_ENABLED=false</code>.</li><li>Run <code>pnpm providers:check</code>, then <code>pnpm dev</code>. Connect and sign with a real wallet.</li></ol><p>The full guide is in <code>docs/API_SETUP.md</code>. Adding API keys does not deploy contracts or enable real stakes.</p></section></div>;}
function Legal({privacy}:{privacy:boolean}){return <div className="page info-page"><span className="eyebrow">BETA TEMPLATE · LEGAL REVIEW REQUIRED</span><h1>{privacy?'Privacy.':'Beta terms.'}</h1><p className="info-intro">This is an operational disclosure and a template for the project owner’s legal review. It is not a finalized legal policy.</p>{privacy?<><h2>What the application stores</h2><p>Wallet addresses, optional usernames, signed authentication challenges, hashed session identifiers, duel records, public blockchain observations, predictions, and points ledgers. Authentication uses an HttpOnly session cookie. Demo mode stores illustrative records separately.</p><h2>Requests and diagnostics</h2><p>Server request logs include an opaque correlation ID, route, status, and timing. Rate limits use short-lived, hashed network identifiers. No advertising trackers or device fingerprints are included. Blockchain and market-data providers receive server requests needed for wallet analytics.</p><h2>Before public launch</h2><p>The owner must supply the operating entity, contact details, retention periods, user-rights process, and applicable jurisdiction. Blockchain records are public and cannot be erased by this application.</p></>:<><h2>Beta access</h2><p>The beta uses simulated stakes and points without cash value. It does not provide trading execution, custody, or guaranteed market data. You control your wallet and are responsible for any trading you perform outside the application.</p><h2>Competition rules</h2><p>Duels use the methodology displayed in the <Link to="/rules">rulebook</Link>. Results can be delayed or disputed when provider coverage is incomplete. Do not manipulate liquidity, falsify records, or interfere with the service.</p><h2>Before public launch</h2><p>The owner must supply an operating entity, eligibility and jurisdiction rules, dispute process, limitation terms, contact details, and a reviewed policy for any future real-money feature. Real-money features remain disabled in this build.</p></>}</div>;}
