import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowUpRight, Search, Trophy } from 'lucide-react';
import { useApp } from '../app';
import { Avatar, ChainBadge, Empty, Return } from '../components/ui';
import { CHAINS } from '@shared/config';
import { nameOf } from '../lib/api';
export default function Leaderboard(){const {data}=useApp();const [metric,setMetric]=useState('wins');const [chain,setChain]=useState('all');const [search,setSearch]=useState('');const traders=data.traders.filter(p=>(chain==='all'||p.chain===chain)&&p.stats.total>=(metric==='winRate'?5:1)&&`${p.username} ${p.wallet}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>b.stats[metric as 'wins'|'winRate'|'averageReturn'|'streak']-a.stats[metric as 'wins'|'winRate'|'averageReturn'|'streak']);
  return <div className="page"><div className="page-heading"><div><span className="eyebrow">EARN YOUR PLACE</span><h1>All receipts. No hype.</h1><p>Ranked by completed duels. Reputation backed by performance.</p></div><Trophy className="heading-icon" size={50}/></div><div className="leaderboard-controls"><div className="segmented large">{[['wins','Most wins'],['winRate','Win rate'],['averageReturn','Average return'],['streak','Win streak']].map(([v,label])=><button key={v} className={v===metric?'selected':''} onClick={()=>setMetric(v)}>{label}</button>)}</div><select aria-label="Leaderboard chain" value={chain} onChange={e=>setChain(e.target.value)}><option value="all">All chains</option>{data.chains.map(c=><option key={c} value={c}>{CHAINS[c].name}</option>)}</select></div><div className="search-field board-search"><Search size={16}/><input aria-label="Search traders" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find a trader or wallet"/></div><div className="table-panel"><table className="leader-table"><thead><tr><th>RANK</th><th>TRADER</th><th>RECORD</th><th>WIN RATE</th><th>AVG. RETURN</th><th>STREAK</th><th/></tr></thead><tbody>{traders.map((p,i)=><tr key={p.id}><td className={`table-rank ${i<3?'podium':''}`}>{i===0?<Trophy size={18}/>:String(i+1).padStart(2,'0')}</td><td><Link className="table-trader" to={`/trader/${p.id}`}><Avatar profile={p}/><span><strong>{nameOf(p)}</strong><ChainBadge chain={p.chain}/></span></Link></td><td>{p.stats.wins}<span className="muted">W / </span>{p.stats.losses}<span className="muted">L</span></td><td>{p.stats.winRate.toFixed(1)}%</td><td><Return value={p.stats.averageReturn}/></td><td><span className={p.stats.streak>0?'streak':''}>{Math.abs(p.stats.streak)}{p.stats.streak>=0?'W':'L'}</span></td><td><Link to={`/challenge?opponent=${encodeURIComponent('@'+p.username)}&chain=${p.chain}`} className="text-button">Call out <ArrowUpRight size={14}/></Link></td></tr>)}</tbody></table>{!traders.length&&<Empty title="This spot is open." description="Complete a duel to earn a place on the leaderboard."/>}</div><p className="table-footnote">{metric==='winRate'?'A minimum of five completed duels is required for win-rate rankings.':'Only completed duels count. Ties are included in the total duel count.'} {data.mode==='demo'?'All records shown are from demo fixtures.':''}</p></div>;
}
