import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { ArrowUpRight, Copy, ExternalLink, Plus, UserCheck, Wallet } from 'lucide-react';
import { linkedWallets } from '@shared/portfolio';
import { CHAINS } from '@shared/config';
import type { DuelView, Profile, Snapshot, Stats } from '@shared/types';
import { useApp } from '../app';
import { Avatar, ChainBadge, DuelCard, Empty, ErrorPanel, Portfolio, Return, Skeleton } from '../components/ui';
import { api, nameOf, short } from '../lib/api';
export default function ProfilePage(){const {id}=useParams();const {data,connect,toast,refresh}=useApp();const query=useQuery({queryKey:['profile',id],queryFn:()=>api<{profile:Profile;stats:Stats;duels:DuelView[]}>(`/traders/${id}`)});const [tab,setTab]=useState('duels'),[username,setUsername]=useState(''),[busy,setBusy]=useState(false);const liveWallet=useQuery({queryKey:['portfolio',id],queryFn:()=>api<Snapshot>('/portfolio'),enabled:tab==='wallet'&&data.profile?.id===query.data?.profile.id&&data.mode==='live',retry:0,staleTime:300000});
  if(query.isPending)return <Skeleton/>;if(query.error)return <ErrorPanel error={query.error}/>;const {profile:p,stats,duels}=query.data;const self=data.profile?.id===p.id;const followed=data.profile?.following.includes(p.id);const active=duels.filter(d=>d.status==='ACTIVE'||d.status==='OPEN');const history=duels.filter(d=>d.status==='COMPLETED');
  const follow=async()=>{if(!data.profile){connect();return;}try{await api(`/follow/${p.id}`,{method:'POST',body:{}});await refresh();toast(followed?'Trader unfollowed':'Trader followed');}catch(e){toast((e as Error).message);}};
  const update=async()=>{setBusy(true);try{await api('/profile',{method:'PATCH',body:{username}});await refresh();toast('Username updated');}catch(e){toast((e as Error).message);}finally{setBusy(false);}};
  return <div className="page profile-page"><div className="profile-hero panel"><Avatar profile={p} size={86}/><div className="profile-identity"><div><h1>{nameOf(p)}</h1><ChainBadge chain={p.chain}/>{p.demo&&<span className="demo-label">DEMO</span>}</div><p><code>{short(p.wallet)}</code><button className="icon-button" aria-label="Copy wallet address" onClick={()=>void navigator.clipboard.writeText(p.wallet).then(()=>toast('Wallet copied'))}><Copy size={14}/></button>{!p.demo&&<a href={`${CHAINS[p.chain].explorer}/address/${p.wallet}`} target="_blank" rel="noreferrer" aria-label="Open wallet in explorer"><ExternalLink size={14}/></a>}</p><span className="reputation">{stats.wins>=10?'PROVEN CONTENDER':stats.wins>=5?'RISING CONTENDER':'IN THE ARENA'}</span></div><div className="profile-actions">{self&&<button className="button secondary" onClick={connect}><Wallet size={16}/>Link wallets</button>}{!self&&<><Link className="button primary" to={`/challenge?opponent=${encodeURIComponent(p.username?'@'+p.username:p.wallet)}&chain=${p.chain}`}>Call them out <ArrowUpRight size={16}/></Link><button className="button secondary" onClick={()=>void follow()}>{followed?<UserCheck size={15}/>:<Plus size={15}/>} {followed?'Following':'Follow trader'}</button></>}</div></div>
    <div className="profile-stats">{[{label:'DUEL RECORD',value:<>{stats.wins}<span>W</span> {stats.losses}<span>L</span> {stats.ties}<span>T</span></>},{label:'WIN RATE',value:`${stats.winRate.toFixed(1)}%`},{label:'AVERAGE RETURN',value:<Return value={stats.averageReturn}/>},{label:'BEST DUEL',value:<Return value={stats.bestReturn}/>},{label:'CURRENT STREAK',value:`${Math.abs(stats.streak)}${stats.streak>=0?'W':'L'}`}].map(item=><div key={item.label}><span>{item.label}</span><strong>{item.value}</strong></div>)}</div>
    <div className="explore-tabs">{[['duels','Live duels'],['history','Duel history'],['rivals','Rivalries'],...(self?[['settings','Your profile'],['wallet','Your portfolios']]:[])].map(([v,label])=><button key={v} className={tab===v?'active':''} onClick={()=>setTab(v)}>{label}</button>)}</div>
    {tab==='duels'||tab==='history'?((tab==='duels'?active:history).length?<div className="card-grid">{(tab==='duels'?active:history).map(d=><DuelCard key={d.id} duel={d}/>)}</div>:<Empty title={tab==='duels'?'No active rivalries.':'No completed duels yet.'} description="Every reputation starts with a first challenge." action={<Link to="/challenge" className="button primary">Create a duel</Link>}/>):tab==='rivals'?<div className="rivals-list">{[...new Set(history.map(d=>d.challenger===p.id?d.opponent:d.challenger))].map(rivalId=>{const list=history.filter(d=>d.challenger===rivalId||d.opponent===rivalId);const rival=data.traders.find(v=>v.id===rivalId)!;return <div className="panel rival-row" key={rivalId}><Avatar profile={rival}/><div><h3>{nameOf(p)} vs {nameOf(rival)}</h3><p>{list.length} duels · {list.filter(d=>d.winner===p.id).length} wins for {nameOf(p)}</p></div><Link className="button secondary" to={`/challenge?opponent=@${rival.username}&chain=${rival.chain}`}>Run it back <ArrowUpRight size={14}/></Link></div>;})}</div>:tab==='settings'?<div className="panel settings-panel"><h2>A name they’ll remember.</h2><p>Your wallet is your identity. Your username makes it easier to find you.</p><label className="field">Username<input value={username} placeholder={p.username||'your_name'} onChange={e=>setUsername(e.target.value.toLowerCase())} minLength={3} maxLength={20}/></label><p className="field-help">3–20 lowercase letters, numbers, or underscores. Changes are limited to once every seven days.</p><button className="button primary" disabled={busy||username.length<3} onClick={()=>void update()}>Save username</button></div>:data.mode==='demo'?<Empty title="Your live wallet belongs here." description="Turn off demo mode after adding the provider keys to inspect real wallet balances." action={<Link className="button secondary" to="/setup">Open setup guide</Link>}/>:liveWallet.isPending?<div className="panel settings-panel"><Wallet size={24}/><p>Reading finalized balances and reference prices…</p></div>:liveWallet.error?<ErrorPanel error={liveWallet.error} retry={()=>void liveWallet.refetch()}/>:<div className="panel settings-panel"><h2>Your combined portfolio</h2><p>{linkedWallets(p).length} linked wallets across {data.chains.length} chains. Each wallet stays in your control.</p><div className="linked-wallets">{linkedWallets(p).map(w=><p key={w.family}><strong>{w.family==='solana'?'Solana':'EVM'}</strong> <code>{short(w.address)}</code><button className="icon-button" aria-label={`Copy ${w.family} address`} onClick={()=>void navigator.clipboard.writeText(w.address).then(()=>toast('Wallet copied'))}><Copy size={14}/></button></p>)}</div><button className="text-button" onClick={connect}>Manage linked wallets</button><Portfolio snapshot={liveWallet.data}/>{liveWallet.data?.issues.map(i=><p key={i} className="notice-box warning">{i}</p>)}</div>}
  </div>;
}
